"""add attendance_sessions, fk records session_id

Revision ID: 938b90f067b2
Revises: 9a58d368cd11
Create Date: 2026-09-10 20:48:03.835545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '938b90f067b2'
down_revision: Union[str, Sequence[str], None] = '9a58d368cd11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'attendance_records', 'attendance_sessions', ['session_id'], ['id'])
    # NOTE (DBAgent review): autogenerate also emitted
    # op.drop_index('student_biometrics_embedding_idx', ...) here. Removed:
    # that HNSW index was created via raw SQL in the initial migration, so it
    # is invisible to autogenerate's metadata comparison. Dropping it would
    # destroy the vector index TSK-103/TSK-204 depend on.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendance_records', type_='foreignkey')
    op.drop_table('attendance_sessions')
    # ### end Alembic commands ###
